# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 414a4647778c0f803445db7fe5888254b9b334eb4dbaee74a46540846d5ff6b50371a29a056c96227c5d5e63b2696fcfe11aeb0427550a053b60c119eba8a69b

test:
  secret_key_base: 14a302be22fafe7a5951bdce0b16636d114179a0ef51138f9fbed6be236d8ea0343140904ed74f7ee54835701a9aac2a27349159fd08cf93a2584fb84800746b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
